[package]
name = "PGCite"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
regex = "1.10.5"
lazy_static = "1.5.0"
url = "2.5.2"
mediawiki = "0.3.1"
serde_json = "1.0.120"
